### ISSUE TITLE
How to answer the questions   about  "The Advertising Identifier (IDFA)"

### ISSUE THREAD

**Issue by auliving** [worona/worona-wp-plugin#34]
My website has google adsense ads.
When submit ios app to review, 
How to answer the questions   about  "The Advertising Identifier (IDFA)"
https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Chapters/SubmittingTheApp.html

**Comment by Poliuk** [comment]
Hello @auliving, 

First of all, the Worona App is independent of your Google Adsense Ads. In any case, the app has the Google AdMob library installed and it will be ready to display Ads as soon as we release the Ads Extension. 

That's why you have to answer "Yes" to the IDFA question and mark the 4 checkboxes. So you won't have any problems in the future if you activate the Ads.

Regards,
Pablo
